obstacle_range: 5.1 #5.0
raytrace_range: 5.5 #5.5

footprint: [ [-0.109, -0.051], [-0.109, 0.051], [0.023, 0.051], [0.023, -0.051] ]  #添加rfid尺寸
#robot_radius: 0.17

cost_scaling_factor: 10.0
transform_tolerance: 0.4

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

inflation_layer: #膨胀层，在以上两层地图进行膨胀，以避免机器人的撞上障碍物，用于路径规划。
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.02  # max. distance from an obstacle at which costs are incurred for planning paths.
################################################################################################################
