global_costmap:
  global_frame: map
  robot_base_frame: base_link #base_footprint

  update_frequency:  10.0 #10.0
  publish_frequency: 10.0 #10.0
  transform_tolerance: 0.2 #0.5

  static_map: true

  footprint: [[-0.109, -0.051], [-0.109, 0.051], [0.023, 0.051], [0.023, -0.051]]
 
  inflation_layer:
    inflation_radius: 0.6 # 你可以在这里设置膨胀半径

  map_type: costmap
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

