global_costmap:
  global_frame: map
  robot_base_frame: base_link #base_footprint

  update_frequency:  3.0 #10.0
  publish_frequency: 3.0 #10.0
  transform_tolerance: 0.8 #0.5

  static_map: true
  rolling_window: false

  footprint: [ [-0.122, -0.057], [-0.127, 0.057], [0.027, 0.057], [0.027, -0.057] ]

  map_type: costmap
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

  inflation_layer: #膨胀层，在以上两层地图进行膨胀，以避免机器人的撞上障碍物，用于路径规划。
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.02  # max. distance from an obstacle at which costs are incurred for planning paths.
