scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: laser

    min_x: -0.001
    max_x: 0.075
    min_y: -0.038
    max_y: 0.038
    min_z: -1.0
    max_z: 1.0

    # min_x: -0.023
    # max_x: 0.109
    # min_y: -0.051
    # max_y: 0.051
    # min_z: -1.0
    # max_z: 1.0
