
footprint: [ [-0.023, -0.051], [-0.023, 0.051], [0.109, 0.051], [0.109, -0.051] ]
footprint_padding: 0.00

transform_tolerance: 1.0 #2.0
map_type: costmap

always_send_full_costmap: true

obstacle_layer:
 enabled: true
 obstacle_range: 1.5
 raytrace_range: 2.5
 inflation_radius: 0.05
 track_unknown_space: true
 combination_method: 1

 observation_sources: scan
 scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

static_layer:
  enabled:              true
  map_topic:            "map"
