obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.023, -0.051], [-0.023, 0.051], [0.109, 0.051], [0.109, -0.051]]

inflation_radius: 0.01
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}