# 全局规划器配置
global_costmap:
  global_frame: "map"      # 使用地图坐标系
  robot_base_frame: "base_link"  # 小车的基准坐标系
  update_frequency: 1.0    # 更新频率
  publish_frequency: 0.5   # 发布频率
  transform_tolerance: 0.5
  resolution: 0.05         # 地图分辨率
  rolling_window: false    # 全局地图不使用滚动窗口
  width: 20.0              # 全局地图宽度（米）
  height: 20.0             # 全局地图高度（米）

  static_map: true         # 使用静态地图
  map_topic: "map"         # 地图话题

  # 全局规划器的成本设置
  plugins:
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: static_layer, type: "costmap_2d::StaticLayer"}

  inflation_layer:
    inflation_radius: 0.55  # 膨胀半径
    cost_scaling_factor: 10.0

# 局部规划器配置
local_costmap:
  global_frame: "odom"     # 使用里程计坐标系
  robot_base_frame: "base_link"  # 小车的基准坐标系
  update_frequency: 5.0    # 更新频率
  publish_frequency: 2.0   # 发布频率
  transform_tolerance: 0.5
  static_map: false        # 不使用静态地图
  rolling_window: true     # 使用滚动窗口
  width: 4.0               # 局部地图宽度（米）
  height: 4.0              # 局部地图高度（米）
  resolution: 0.02         # 地图分辨率

  # 局部规划器的成本设置
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}

  inflation_layer:
    inflation_radius: 0.55
    cost_scaling_factor: 10.0

# Move Base 参数配置
controller_frequency: 10.0    # 控制器更新频率
planner_patience: 5.0         # 全局规划器超时时间
controller_patience: 3.0      # 局部规划器超时时间
max_planning_retries: 5       # 全局规划器最大尝试次数

planner_frequency: 1.0        # 全局规划器更新频率
recovery_behavior_enabled: true # 是否启用恢复行为

# 全局规划器的设置
base_global_planner: "navfn/NavfnROS"  # 使用 navfn 作为全局路径规划器

# 局部规划器的设置
base_local_planner: "dwa_local_planner/DWAPlannerROS"  # 使用 DWA 作为局部路径规划器

# DWA 局部规划器的参数配置
DWAPlannerROS:
  max_vel_x: 0.08              # 最大线速度
  min_vel_x: 0.05              # 最小线速度
  max_vel_theta: 0.15          # 最大角速度
  min_vel_theta: 0.08          # 最小角速度
  acc_lim_x: 2.5              # 线加速度限制
  acc_lim_theta: 2.5          # 角加速度限制
  xy_goal_tolerance: 0.1      # 到达目标点的线距离容忍度
  yaw_goal_tolerance: 0.2     # 到达目标点的角度容忍度
  latch_xy_goal_tolerance: true

  # 控制窗口
  sim_time: 1.0               # 模拟时间
  vx_samples: 20              # x 方向的采样数量
  vtheta_samples: 40          # 角速度的采样数量
  path_distance_bias: 32.0    # 路径距离的偏差
  goal_distance_bias: 24.0    # 目标距离的偏差
  occdist_scale: 0.01         # 障碍物距离的缩放比例

  # 机器人配置
  robot_radius: 0.3           # 机器人半径
  forward_point_distance: 0.325  # 前进点的距离
  stop_time_buffer: 0.2

  # 碰撞预防
  oscillation_reset_dist: 0.05